// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_P7jRZQstsszOMaNGQYmLo6Bu7E3FlEw',
    appId: '1:268839700175:web:eb87f3b40b1f1b03c7d9ba',
    messagingSenderId: '268839700175',
    projectId: 'thebuildershubb',
    authDomain: 'thebuildershubb.firebaseapp.com',
    storageBucket: 'thebuildershubb.firebasestorage.app',
    measurementId: 'G-Z3WPLGDJXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQ4VqAQ9IE82PjeMrgEgdyu02D9l-YAg',
    appId: '1:268839700175:android:b59a8aaabde33dd6c7d9ba',
    messagingSenderId: '268839700175',
    projectId: 'thebuildershubb',
    storageBucket: 'thebuildershubb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKo6YbujAH0M9PYbPDWxgh0CeFpBuoDjg',
    appId: '1:268839700175:ios:10d2a533da56239bc7d9ba',
    messagingSenderId: '268839700175',
    projectId: 'thebuildershubb',
    storageBucket: 'thebuildershubb.firebasestorage.app',
    androidClientId: '268839700175-56qhdjj3a2n32feoniafmtc99a5og5nd.apps.googleusercontent.com',
    iosClientId: '268839700175-haeui7ts0buj0a3qnmnra755t70f19s1.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.6amMart',
  );

}